import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="align-top">
        <NavBar />
      </div>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
