import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { SignInButton, UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey="pk_test_YWxlcnQtdHJvbGwtMjUuY2xlcmsuYWNjb3VudHMuZGV2JA">
      <html lang="en" className="bg-white">
        <body className="bg-white">
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <div className="align-top">
              <NavBar />
            </div>
            <div className="bg-white">{children}</div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
